#!/bin/sh -e

. /usr/share/debconf/confmodule

setConfigValue() {
	KEY="$1";
	VALUE="$2";
	CONFIG="$3";
	sed -i "s%${KEY}=.*%${KEY}=${VALUE}%g" ${CONFIG}
}

setConfigValueFromDb() {
	KEY="$1";
	DBKEY="$2";
	CONFIG="$3";
	db_get $DBKEY
	setConfigValue "$KEY" "$RET" "$CONFIG"
}